// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_crud.Models;

namespace mvc_crud.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210208105315_soko")]
    partial class soko
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("mvc_crud.Models.Student", b =>
                {
                    b.Property<string>("FirstName")
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("FirstName");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
